language: node_js
node_js:
  - "8"
  - "10"
env:
  - HAPI=hapi@17
  - HAPI=hapi@18
  - JOI=joi@14
  - JOI-joi@13
before_script:
  - npm install --save-dev $HAPI $JOI
after_script:
  - "npm run test-cov-coveralls"
